### ISSUE TITLE
Illegal Math Expression Error for 10^-x

### ISSUE THREAD

**Issue by henryricca** [OpenWaterAnalytics/epanet-msx#4]
MSX doesn't appear to be able to handle expressions in the form of 10^-x.  It handles expressions in the the form of 10^x fine. We discovered this when trying to incorporate temperature dependent equilibrium constants in a chloramine decay model. The following 3 files are in the attached .zip folder, which highlight the issue.

chloramine.inp - EPANET input file for the simple example network provided with the manual

chloramine_temp_issue.msx - MSX input file that produces the error discussed above

chlormaine_temp_issue.rep - report file generated from running 'chloramine.inp' with 'chloramine_temp_issue.msx'. This shows the errors generated when including expressions in the form of 10^-x

[Negative_Power_Issue.zip](https://github.com/OpenWaterAnalytics/epanet-msx/files/1823069/Negative_Power_Issue.zip)

**Comment by samhatchett** [comment]
possible dupe of #1

**Comment by bradleyjeck** [comment]
I ran across something similar working on a [paper](http://bradeck.net/docs/EckSaitoMcKenna2016_waterTemp.pdf) on temp,  chlorine decay, and DBP formation.   The work-around was to use extra parentheses e.g. `( 10^(-x))`  instead of `10^-x`.

**Comment by henryricca** [comment]
Thanks for the quick reply, adding the extra parentheses seems to have solved it!
